[package]
name = "shell"
version = "0.1.0"
source = "main.spz"

[dependencies]
libkurt = { git = "https://github.com/Kurt-OS/libkurt.git", tag = "v0.1.0-dev" }

[targets]
default = ["https://github.com/Kurt-OS/kurt.target@v0.1.0-dev"]
